#ENC[AES256_GCM,data:nOghg5qsFQpFDZqBKpZRPsdO6t4OO9sne/UMcwO+dhxz4+TfB89T2AT2f/2iMAsUzNEh26uyFW2f09VzrOrAwW1FPfvPn5zmJp+m,iv:wx8DBambYeMF4UKOmajaTrjJLAe/QGD+5vBaXdqjxsg=,tag:gcmzFBPYH1joOp3raGFaZA==,type:comment]
#ENC[AES256_GCM,data:ocE8FhyjreaFsTKzmW7Mq7LJC+IAwxnKNerVAOLZgsAsD0c6oBO1syYkZg==,iv:ffRNomj3j0IpnEWXONE5b22i3+nzbzXsT9d6FhlBVV4=,tag:VfmcsTK6XsGIroy3k33FDg==,type:comment]
#ENC[AES256_GCM,data:uhhiSfE7Fn1rWK+fb7VCe/9Bv6bHliTz61t16SqLCPaPuLbRMcA9QPwX9x7chiI=,iv:UEIZBAlPEPN8CrUzc9oFPLsw2WeZedcB/sK5oR++T4k=,tag:sXLhEoZYUeIsYbawSftqWA==,type:comment]
cloudflare_api_token: ENC[AES256_GCM,data:lsqY7UCZP+emV0IWVWm1gjmwnXXimGg17JIFfCnUYPHvXIq5jNZQ0hxKToizCimRcEtUqfc=,iv:bkU7CY7kyvDahf3f5MIUD5mARdvW1w0TqSoUU4Ge0sc=,tag:iT77WtZbRQo/dPlxhjGaoA==,type:str]
#ENC[AES256_GCM,data:UHBfnGnffttSZQUocnkMrhKrBQeJ8PXObiDgDJyf1dFr1GU1jMf1U7srIsnlVZeqzw==,iv:tWr8mocyXzY8CqBWshD9o9/7BfTJB655sAfrbtgKKkY=,tag:M3QZiCUa3yhXDp+O1YMJhg==,type:comment]
b2_account_id: ENC[AES256_GCM,data:cMdIhsT7rkk0Js1CqG5yn8ML6zmoCngg3A==,iv:+rad7d+t2SlQrWfvg5BZrW8VllHHfKTcdcf8yBgrY4w=,tag:wVHf/IfxaBGzOdMhAIY5Og==,type:str]
b2_account_key: ENC[AES256_GCM,data:VhAddwQbbT3thtGuBtjawUPCrf29DHlyqgXmnjsMDw==,iv:R1dZfmkcwCnyB3l07LN1RRrz48vUYqWrP7VvQZDsP7U=,tag:FSz6qI9z7D5Jsb3vWwBCcQ==,type:str]
b2_bucket: ENC[AES256_GCM,data:AnXNGxqKBk+6jPR6kg==,iv:nHTsNpRCWIwBnpk9aQcsA9oijEfKEZGDFKBjoLtM6Yc=,tag:3mSzfogJVWpZjIV6CBp4Uw==,type:str]
#ENC[AES256_GCM,data:QspJdyXkrVQHXmm/YJJ46rqJkjynBjS7xI5y6uOefbRWcuA2Lvpte6jjvu1S9wcEDsIPpUSG7Qw3BTw8VIFDxMO/TOYWIGIhclLR,iv:alifBlBTU2zFhpfWF/ElFt7G7wN4YTRNhvgvM1yOONk=,tag:AeDfIh1V4Iyinla18hnxcw==,type:comment]
#ENC[AES256_GCM,data:f+0cY5ZQ2yW4iwxEKXTFj7mTP6uePMbG/hyCgzg/L9mVVJlaJ6d16WLqgqTPIdkc8zM0Ail8KCXqmD37sy1b6zZDCgon1LQhag==,iv:1bL4v6J/SCqbY1wwLPeH3jddgyajr/8moKrlLZuC63A=,tag:D3jAGakG/trHvVJxz5vWdg==,type:comment]
#ENC[AES256_GCM,data:X13XUFH/rC5GnVH9gwgxBHVP3TC4ZpxF/GnChqVpl2uyFUNALDCo/TAWT6gv1LoIugoCVSDOfTU=,iv:qa5INDeF7LEVbW4YLWmpf/kOPftLkFVKSJ5ctQfx35c=,tag:EZK0U0Dxn4zKg/PUIVgFXA==,type:comment]
restic_password: ENC[AES256_GCM,data:aN5MDiGW3HUQGrrIgHcZDEGobgVar9tyxhPvdZuLKyA/TgbssPWajVtH/ck=,iv:C1fqwxIY1sBYoO4TYsP4ZPfWVcb+iQR7+K1DWnU7l20=,tag:m5wIHSCFiRxTEObDQUhGIw==,type:str]
samba_mark_password: ENC[AES256_GCM,data:aYEMKsFidg==,iv:dh/TpNWWAQDq56kenA5ijUGpDF4YvJTyWzOHkNh/Mrc=,tag:FjERMCg40B6eXXWSzAAHrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNTNVUnBSTm8rSXpVdW1W
            Qi8zWVhpb3kwVncxRmVWcFh6Z3ZJMHZqUFdJCkRjRmVlVG9nNEJUcTFGZTNhNTBI
            NExsNGd0WUNpRy8rbm9MZDZlQmc2WUkKLS0tIHRzS3djNU5UVnBIR0NsVHRyenh2
            VjViUU5wMUtST29MUFVpNGhIRHl6UzAKkKdf4QVmulj6FYfAo6qadf1jfM7qw0wf
            wDtmtNCXESHXaDilKuOF6H0UX1IgsVtwmSqKAg3Z6Zv0cBiiG/thQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nzfym3k4ptyua53p8v5e0m8qvfyjkytcms8nkrdcm3fd44a0m92s38lssv
    lastmodified: "2026-08-17T01:04:01Z"
    mac: ENC[AES256_GCM,data:i5h9f1btlHBqBVH8f1MnlLmPcT56tu63uMDDiUBE29/fSU+jAd22Emn7hXhyZ35TajmS5Mt+/54pIHTrK5khiczKEHP4F0iImsnwpAXVS4sU/Rxqydb3pIS7AJhp7GbHrOcY5DsuGztM3kFb/NZuoYRuE2jSkGRKSo+XT7gPV+s=,iv:NeWz++gxdO2OWSgCbYmBTBMgPFvYMMPEXfzViwyf/3c=,tag:Y5y2iKLojqY7MBgDgGYYIg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
